name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install modules
        run: pnpm install --no-frozen-lockfile

      - name: Check linting
        run: pnpm lint

