name: publish-react-native

on:
  workflow_dispatch:
  release:
    types: [created]
    paths:
      - "packages/react-native/**"

jobs:
  publish-npm-registry:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./packages/react-native

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dooboo'

      - name: Install modules
        run: npm install

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
