name: publish-node

on:
  workflow_dispatch:
  release:
    types: [created]
    paths:
      - "packages/node/**"

jobs:
  publish-npm-registry:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./packages/node

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dooboo'

      - name: Install modules
        run: npm install

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish-github-registry:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: ./packages/node

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://npm.pkg.github.com'
  #         scope: '@dooboo'

  #     - name: Install modules
  #       run: npm install

  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
